# 6/20 練習

In [1]:
2+2

4

In [2]:
print('hello')

hello


In [3]:
for i in range(5):
    print(i)
    

0
1
2
3
4


# numpy 練習

In [1]:
import numpy as np
my_list = [1,2,3,4]

In [4]:
my_array1 = np.array(my_list)

In [6]:
my_array1

array([1, 2, 3, 4])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(5,50,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [12]:
5/2

2.5

In [13]:
from __future__ import division

In [14]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [15]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [16]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [17]:
arr1 -arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
arr1 **3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)